export const httpStatuses = {
    100: "Continue",
    101: "Switching Protocols",
    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-Authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    300: "Multiple Choices",
    301: "Moved Permanently",
    302: "Found",
    303: "See Other",
    304: "Not Modified",
    305: "Use Proxy",
    307: "Temporary Redirect",
    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not Found",
    405: "Method Not Allowed",
    406: "Not Acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Request Entity Too Large",
    414: "Request-URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Satisfiable",
    417: "Expectation Failed",
    500: "Internal Server Error",
    501: "Not Implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
};

export const statusMessages = {
    300: "Multiple Choices - There are multiple options available for the requested URL",
    301: "Moved Permanently - The requested URL has been permanently moved to a new location",
    302: "Found - The requested URL has been temporarily moved to a different location",
    303: "See Other - The response to the request can be found under a different URI",
    304: "Not Modified - The URL has not been modified since the version specified by the request headers",
    305: "Use Proxy - The requested URL must be accessed through the proxy given by the Location field",
    307: "Temporary Redirect - The requested URL is temporarily under a different URI",
    400: "Bad Request - Your payload is incorrect. Recheck your payload before trying.",
    401: "Unauthorized - Authentication required to access this endpoint.",
    402: "Payment Required - You need to pay to access this endpoint.",
    403: "Forbidden - You don't have permission to access this URL",
    404: "Not Found - The URL might be incorrect. Recheck it before trying.",
    405: "Method Not Allowed - The method specified in the request is not allowed for the URL",
    406: "Not Acceptable - The server cannot produce a response matching the list of acceptable values defined in the request headers",
    407: "Proxy Authentication Required - The client must first authenticate itself with the proxy",
    408: "Request Timeout - The server timed out waiting for the request",
    409: "Conflict - The request could not be completed due to a conflict with the current state of the URL",
    410: "Gone - The requested URL is no longer available at the server",
    411: "Length Required - The server requires a content-length in the request",
    412: "Precondition Failed - One of the conditions in the request header fields evaluated to false",
    413: "Request Entity Too Large - The request is larger than the server is willing or able to process",
    414: "Request-URI Too Long - The URI provided was too long for the server to process",
    415: "Unsupported Media Type - The server does not support the request content type",
    416: "Requested Range Not Satisfiable - The client has asked for a portion of the file, but the server cannot supply that portion",
    417: "Expectation Failed - The server cannot meet the requirements of the Expect request-header field",
    500: "Internal Server Error - The server has encountered some issues.",
    501: "Not Implemented - The server does not support the functionality required to fulfill the request",
    502: "Bad Gateway - The server, while acting as a gateway or proxy, received an invalid response from the upstream server",
    503: "Service Unavailable - The server is currently unable to handle the request",
    504: "Gateway Timeout - The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server",
    505: "HTTP Version Not Supported - The server does not support the HTTP protocol version that was used in the request",
};
